In [39]:
import numpy as np

"11" За квадратною матрицею одержати послідовність чисел обходом матриці "спіраллю" за
годинниковою стрілкою, розпочавши обхід у лівому верхньому куті.

In [124]:
n = 5
a = np.zeros((n,n), dtype=np.int32)


In [125]:
def _AB(t, a, num):
    n = a.shape[0]
    i = t
    for j in range(t, n-t-1):
        a[i,j] = num
        num += 1
    return num

In [126]:
def _BC(t, a, num):
    n = a.shape[0]
    j = n-t-1
    for i in range(t, n-t-1):
        a[i,j] = num
        num +=1
    return num

In [127]:
def _CD(t, a, num):
    n = a.shape[0]
    i = n-t-1
    for j in range(n-t-1, t, -1):
        a[i,j] = num
        num += 1
    return num

In [128]:
def _DA(t, a, num):
    n = a.shape[0]
    j = t
    for i in range(n-t-1, t, -1):
        a[i,j] = num
        num += 1
    return num

In [129]:
def move(t, a, num):
    num = _AB(t, a, num)
    num = _BC(t, a, num)
    num = _CD(t, a, num)
    num = _DA(t, a, num)
    return num

In [130]:
def spiral(a):
    n=a.shape[0]
    m=n//2
    num=1
    for t in range(m):
        num = move(t, a, num)
    if n%2:
        a[m, m]=num
        n += 1


In [131]:
spiral(a)
a

array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19,  6],
       [15, 24, 25, 20,  7],
       [14, 23, 22, 21,  8],
       [13, 12, 11, 10,  9]])

"12" За квадратною матрицею одержати послідовність чисел обходом "змійкою" трикутника над головною
діагоналлю матриці, розпочавши обхід у правому верхньому куті та рухаючись діагоналями.

In [161]:
n = 8
a = np.zeros((n,n), dtype=np.int32)
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [162]:
def _down(t,a,num):
    n=a.shape[0]
    i=0
    j=t
    while j<n:
        a[i,j]=num             
        i+=1
        j+=1
        num+=1
    return num

In [163]:
def _up(t,a,num):
    n=a.shape[0]
    i=n-t-1
    j=n-1
    while i>=0:
        a[i,j]=num       
        i-=1
        j-=1
        num+=1
    return num

In [165]:
def snake(a):
    n = a.shape[0]
    num = 1
    t=n-1
    for _ in range(n//2):
        num=_up(t,a,num)
        t-=1
        num=_down(t,a,num)
        t-=1
    if t>=0:
        num=_up(t,a,num)
    return num

In [166]:
snake(a)
a

array([[29, 28, 16, 15,  7,  6,  2,  1],
       [ 0, 30, 27, 17, 14,  8,  5,  3],
       [ 0,  0, 31, 26, 18, 13,  9,  4],
       [ 0,  0,  0, 32, 25, 19, 12, 10],
       [ 0,  0,  0,  0, 33, 24, 20, 11],
       [ 0,  0,  0,  0,  0, 34, 23, 21],
       [ 0,  0,  0,  0,  0,  0, 35, 22],
       [ 0,  0,  0,  0,  0,  0,  0, 36]])